version: "3.9"
services:
  {{cookiecutter.project_slug}}:
    image: {{cookiecutter.project_slug}}:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    # volumes:
    #   - /Users/nicholas/Databases:/app/DatabasesMount
    env_file:
      - .env.dev
