version: "3.9"
services:
  {{cookiecutter.project_slug}}:
    image: {{cookiecutter.project_slug}}:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "{{cookiecutter.dev_host_port}}:{{cookiecutter.app_port}}"
    # volumes:
    #   - /Users/nicholas/Databases:/app/DatabasesMount
    env_file:
      - .env
