# Reusable workflow for building, testing, and optionally deploying.
name: Build and (Optional) Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      deploy:
        required: false
        type: boolean
        default: false
      container_name:
        required: false
        type: string
      port:
        required: false
        type: string

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: "{% raw %}${{ inputs.environment }}{% endraw %}"
    outputs:
      image: "{% raw %}${{ steps.image.outputs.image }}{% endraw %}"
    steps:
      - uses: actions/checkout@v4

      - name: Set image name
        id: image
        run: "echo \"image={{cookiecutter.ghcr}}/{{cookiecutter.project_slug}}:{% raw %}${{ inputs.image_tag }}{% endraw %}\" >> $GITHUB_OUTPUT"

      - name: Python Build and Test
        uses: ./.github/actions/python-build-test
        with:
          python-version: '{{cookiecutter.python_version}}'

      - name: Build & Push Image
        uses: ./.github/actions/build-to-ghcr
        with:
          image: "{% raw %}${{ steps.image.outputs.image }}{% endraw %}"
          extra_tag: "{% raw %}${{ github.sha }}{% endraw %}"
          build_context: '{{cookiecutter.project_slug}}'
          github_token: "{% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}"
          github_actor: "{% raw %}${{ github.actor }}{% endraw %}"

  deploy:
    if: "{% raw %}${{ inputs.deploy == true }}{% endraw %}"
    needs: build-test
    runs-on: self-hosted
    environment: "{% raw %}${{ inputs.environment }}{% endraw %}"
    steps:
      - name: Deploy container
        uses: ./.github/actions/deploy-docker-local
        with:
          image: "{% raw %}${{ needs.build-test.outputs.image }}{% endraw %}"
          name: "{% raw %}${{ inputs.container_name }}{% endraw %}"
          port: "{% raw %}${{ inputs.port }}{% endraw %}"
          github_token: "{% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}"
          github_actor: "{% raw %}${{ github.actor }}{% endraw %}"
