name: 'Build and Push Docker Image to GHCR'
description: 'Builds a Docker image and pushes it to GitHub Container Registry (GHCR)'
inputs:
  image:
    description: 'Base Docker image name (including tag)'
    required: true
  extra_tag:
    description: 'Optional extra tag (e.g. commit SHA)'
    required: false
  build_context:
    description: 'Docker build context directory'
    required: true
  github_token:
    description: 'GitHub token for registry login'
    required: true
  github_actor:
    description: 'GitHub actor for registry login'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Log in to GHCR
      shell: bash
      run: |
        echo "{% raw %}${{ inputs.github_token }}{% endraw %}" | docker login ghcr.io -u "{% raw %}${{ inputs.github_actor }}{% endraw %}" --password-stdin
    - name: Build image
      shell: bash
      run: |
        set -euo pipefail
        if [ -n "{% raw %}${{ inputs.extra_tag }}{% endraw %}" ]; then
          docker build -t "{% raw %}${{ inputs.image }}{% endraw %}" -t "{% raw %}${{ inputs.image }}{% endraw %}-{% raw %}${{ inputs.extra_tag }}{% endraw %}" "{% raw %}${{ inputs.build_context }}{% endraw %}"
        else
          docker build -t "{% raw %}${{ inputs.image }}{% endraw %}" "{% raw %}${{ inputs.build_context }}{% endraw %}"
        fi
    - name: Push image
      shell: bash
      run: |
  docker push "{% raw %}${{ inputs.image }}{% endraw %}"
  if [ -n "{% raw %}${{ inputs.extra_tag }}{% endraw %}" ]; then docker push "{% raw %}${{ inputs.image }}{% endraw %}-{% raw %}${{ inputs.extra_tag }}{% endraw %}"; fi
